id: A26AA7BB1
title: Prayer to Jamgön Kongtrul Lodrö Thayé
type: translation
pechas:
- IE1D8E18E
- IE5788D8E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:24.088555
  last_modified_at: 2023-01-04 12:01:24.088562
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  IE1D8E18E/4053: 2DC2
  IE5788D8E/C63D: 2DC2
